# Generated by Django 3.2.4 on 2021-06-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=200)),
            ],
        ),
    ]
